/**
 * Environment variable parsing utilities
 *
 * Handles parsing KEY=VALUE strings and .env files for the CLI
 */
import fs from 'fs-extra';
import path from 'path';

/**
 * Reserved environment variable keys (AWS Lambda internal)
 * These should not be modified by users
 */
export const RESERVED_ENV_KEYS = [
  'AWS_REGION',
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_SESSION_TOKEN',
  'AWS_LAMBDA_FUNCTION_NAME',
  'AWS_LAMBDA_FUNCTION_MEMORY_SIZE',
  'AWS_LAMBDA_FUNCTION_VERSION',
  'AWS_LAMBDA_LOG_GROUP_NAME',
  'AWS_LAMBDA_LOG_STREAM_NAME',
  '_HANDLER',
  '_X_AMZN_TRACE_ID',
];

/**
 * System environment variable keys set by Lambda Web Adapter
 */
export const SYSTEM_ENV_KEYS = [
  'PORT',
  'AWS_LWA_PORT',
  'AWS_LWA_INVOKE_MODE',
  'AWS_LWA_READINESS_CHECK_MIN_UNHEALTHY_STATUS',
];

/**
 * Parse a single KEY=VALUE string
 * Handles various edge cases like quoted values, equals signs in values, etc.
 *
 * @param input - String in format KEY=VALUE
 * @returns Parsed key-value pair or null if invalid
 */
export function parseEnvVar(input: string): { key: string; value: string } | null {
  if (!input || typeof input !== 'string') {
    return null;
  }

  const trimmed = input.trim();
  const equalIndex = trimmed.indexOf('=');

  if (equalIndex === -1) {
    return null;
  }

  const key = trimmed.substring(0, equalIndex).trim();
  let value = trimmed.substring(equalIndex + 1);

  // Handle quoted values
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    value = value.slice(1, -1);
  }

  if (!isValidEnvKey(key)) {
    return null;
  }

  return { key, value };
}

/**
 * Parse .env file content into key-value pairs
 * Handles comments, empty lines, and quoted values
 *
 * @param content - Raw .env file content
 * @returns Record of environment variables
 */
export function parseEnvFile(content: string): Record<string, string> {
  const result: Record<string, string> = {};

  if (!content || typeof content !== 'string') {
    return result;
  }

  const lines = content.split(/\r?\n/);

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip empty lines and comments
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const parsed = parseEnvVar(trimmed);
    if (parsed) {
      result[parsed.key] = parsed.value;
    }
  }

  return result;
}

/**
 * Load and parse a .env file from disk
 *
 * @param filePath - Path to .env file
 * @returns Record of environment variables
 * @throws Error if file cannot be read
 */
export async function loadEnvFile(filePath: string): Promise<Record<string, string>> {
  const absolutePath = path.resolve(filePath);

  if (!(await fs.pathExists(absolutePath))) {
    throw new Error(`Env file not found: ${absolutePath}`);
  }

  const content = await fs.readFile(absolutePath, 'utf-8');
  return parseEnvFile(content);
}

/**
 * Write environment variables to a .env file
 *
 * @param filePath - Path to output file
 * @param vars - Environment variables to write
 */
export async function writeEnvFile(filePath: string, vars: Record<string, string>): Promise<void> {
  const absolutePath = path.resolve(filePath);

  const lines: string[] = [
    '# Environment variables',
    `# Generated by leanmcp CLI at ${new Date().toISOString()}`,
    '',
  ];

  // Sort keys for consistent output
  const sortedKeys = Object.keys(vars).sort();

  for (const key of sortedKeys) {
    const value = vars[key];
    // Quote values that contain special characters
    if (value.includes(' ') || value.includes('#') || value.includes('"')) {
      lines.push(`${key}="${value.replace(/"/g, '\\"')}"`);
    } else {
      lines.push(`${key}=${value}`);
    }
  }

  lines.push(''); // Trailing newline
  await fs.writeFile(absolutePath, lines.join('\n'));
}

/**
 * Validate environment variable key format
 * Keys must start with a letter or underscore, and contain only
 * alphanumeric characters and underscores
 *
 * @param key - Environment variable key to validate
 * @returns true if valid
 */
export function isValidEnvKey(key: string): boolean {
  if (!key || typeof key !== 'string') {
    return false;
  }

  // Must start with letter or underscore
  // Can contain letters, numbers, underscores
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(key);
}

/**
 * Check if a key is reserved (AWS Lambda internal)
 */
export function isReservedKey(key: string): boolean {
  return RESERVED_ENV_KEYS.includes(key);
}

/**
 * Check if a key is a system key (Lambda Web Adapter)
 */
export function isSystemKey(key: string): boolean {
  return SYSTEM_ENV_KEYS.includes(key);
}

/**
 * Parse multiple KEY=VALUE arguments from CLI
 *
 * @param args - Array of KEY=VALUE strings
 * @returns Record of environment variables
 */
export function parseEnvArgs(args: string[]): Record<string, string> {
  const result: Record<string, string> = {};

  for (const arg of args) {
    const parsed = parseEnvVar(arg);
    if (parsed) {
      result[parsed.key] = parsed.value;
    }
  }

  return result;
}

/**
 * Mask sensitive values for display
 *
 * @param vars - Environment variables
 * @returns Variables with values replaced by ***
 */
export function maskValues(vars: Record<string, string>): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, value] of Object.entries(vars)) {
    result[key] = '***';
  }
  return result;
}

/**
 * Format environment variables for display in terminal
 *
 * @param vars - Environment variables
 * @param reveal - Whether to show actual values
 * @returns Formatted string for display
 */
export function formatEnvVarsForDisplay(vars: Record<string, string>, reveal = false): string {
  const keys = Object.keys(vars).sort();

  if (keys.length === 0) {
    return '  (no environment variables)';
  }

  const lines = keys.map((key) => {
    const value = reveal ? vars[key] : '***';
    const keyType = isSystemKey(key) ? ' (system)' : '';
    return `  ${key}=${value}${keyType}`;
  });

  return lines.join('\n');
}
